export const products = [
  {
    id: "001",
    name: "Tomate",
    group: "vegetais",
    image: "tomate.jpg",
  },
  {
    id: "002",
    name: "Batata",
    group: "vegetais",
    image: "batata.jpg",
  },
  {
    id: "003",
    name: "Alface",
    group: "vegetais",
    image: "alface.jpg",
  },
  { id: "004", name: "Maçã", group: "frutas", image: "maca.jpg" },
  { id: "005", name: "Repolho", group: "vegetais", image: "repolho.jpg" },
  { id: "006", name: "Amendoim", group: "cereais", image: "amendoim.jpg" },
  { id: "007", name: "Ovo", group: "origem animal", image: "ovo.jpg" },
  { id: "008", name: "Peixe", group: "carnes", image: "peixe.jpg" },
  { id: "009", name: "Abóbora", group: "vegetais", image: "abobora.jpg" },
  { id: "010", name: "Abobrinha", group: "vegetais", image: "abobrinha.jpg" },
  { id: "011", name: "Acelga", group: "vegetais", image: "acelga.jpg" },
  { id: "012", name: "Agrião", group: "vegetais", image: "agrao.jpg" },
  { id: "013", name: "Aipim", group: "vegetais", image: "aipim.jpg" },
  { id: "014", name: "Alcachofra", group: "vegetais", image: "alcachofra.jpg" },
  { id: "015", name: "Alecrim", group: "vegetais", image: "alecrim.jpg" },
  { id: "016", name: "Alho", group: "vegetais", image: "alho.jpg" },
  { id: "017", name: "Berinjela", group: "vegetais", image: "berinjela.jpg" },
  { id: "018", name: "Beterraba", group: "vegetais", image: "beterraba.jpg" },
  { id: "019", name: "Brócolis", group: "vegetais", image: "brocolis.jpg" },
  { id: "020", name: "Cebola", group: "vegetais", image: "cebola.jpg" },
  { id: "021", name: "Cebolinha", group: "vegetais", image: "cebolinha.jpg" },
  { id: "022", name: "Cenoura", group: "vegetais", image: "cenoura.jpg" },
  { id: "023", name: "Chuchu", group: "vegetais", image: "chuchu.jpg" },
  { id: "024", name: "Couve", group: "vegetais", image: "couve.jpg" },
  { id: "025", name: "Couve-Flor", group: "vegetais", image: "couve-flor.jpg" },
  { id: "026", name: "Erva-Doce", group: "vegetais", image: "erva-doce.jpg" },
  { id: "027", name: "Espinafre", group: "vegetais", image: "espinafre.jpg" },
  { id: "028", name: "Gengibre", group: "vegetais", image: "gengibre.jpg" },
  { id: "029", name: "Hortelã", group: "vegetais", image: "hortela.jpg" },
  { id: "030", name: "Inhame", group: "vegetais", image: "inhame.jpg" },
  { id: "031", name: "Louro", group: "vegetais", image: "louro.jpg" },
  { id: "032", name: "Manjericão", group: "vegetais", image: "manjericao.jpg" },
  { id: "033", name: "Mostarda", group: "vegetais", image: "mostarda.jpg" },
  { id: "034", name: "Nabo", group: "vegetais", image: "nabo.jpg" },
  { id: "035", name: "Palmito", group: "vegetais", image: "palmito.jpg" },
  { id: "036", name: "Pepino", group: "vegetais", image: "pepino.jpg" },
  { id: "037", name: "Pimenta", group: "vegetais", image: "pimenta.jpg" },
  { id: "038", name: "Pimentão", group: "vegetais", image: "pimentao.jpg" },
  { id: "039", name: "Quiabo", group: "vegetais", image: "quiabo.jpg" },
  { id: "040", name: "Rabanete", group: "vegetais", image: "rabanete.jpg" },
  { id: "041", name: "Rúcula", group: "vegetais", image: "rucula.jpg" },
  { id: "042", name: "Salsa", group: "vegetais", image: "salsa.jpg" },
  { id: "043", name: "Salsão", group: "vegetais", image: "salsao.jpg" },
  { id: "044", name: "Tomilho", group: "vegetais", image: "tomilho.jpg" },
  { id: "045", name: "Abacate", group: "frutas", image: "abacate.jpg" },
  { id: "046", name: "Abacaxi", group: "frutas", image: "abacaxi.jpg" },
  { id: "047", name: "Acerola", group: "frutas", image: "acerola.jpg" },
  { id: "048", name: "Ameixa", group: "frutas", image: "ameixa.jpg" },
  { id: "049", name: "Amora", group: "frutas", image: "amora.jpg" },
  { id: "050", name: "Araçá", group: "frutas", image: "araca.jpg" },
  { id: "051", name: "Banana", group: "frutas", image: "banana.jpg" },
  { id: "052", name: "Bergamota", group: "frutas", image: "bergamota.jpg" },
  { id: "053", name: "Butiá", group: "frutas", image: "butia.jpg" },
  { id: "054", name: "Caqui", group: "frutas", image: "caqui.jpg" },
  { id: "055", name: "Carambola", group: "frutas", image: "carambola.jpg" },
  { id: "056", name: "Cereja", group: "frutas", image: "cereja.jpg" },
  { id: "057", name: "Figo", group: "frutas", image: "figo.jpg" },
  { id: "058", name: "Framboesa", group: "frutas", image: "framboesa.jpg" },
  { id: "059", name: "Goiaba", group: "frutas", image: "goiaba.jpg" },
  { id: "060", name: "Laranja", group: "frutas", image: "laranja.jpg" },
  { id: "061", name: "Limão", group: "frutas", image: "limao.jpg" },
  { id: "062", name: "Mamão", group: "frutas", image: "mamao.jpg" },
  { id: "063", name: "Manga", group: "frutas", image: "manga.jpg" },
  { id: "064", name: "Maracujá", group: "frutas", image: "maracuja.jpg" },
  { id: "065", name: "Melancia", group: "frutas", image: "melancia.jpg" },
  { id: "066", name: "Melão", group: "frutas", image: "melao.jpg" },
  { id: "067", name: "Morango", group: "frutas", image: "morango.jpg" },
  { id: "068", name: "Pera", group: "frutas", image: "pera.jpg" },
  { id: "069", name: "Uva", group: "frutas", image: "uva.jpg" },
  { id: "070", name: "Arroz", group: "cereais", image: "arroz.jpg" },
  { id: "071", name: "Ervilha", group: "cereais", image: "ervilha.jpg" },
  { id: "072", name: "Favas", group: "cereais", image: "favas.jpg" },
  { id: "073", name: "Feijão", group: "cereais", image: "feijao.jpg" },
  {
    id: "074",
    name: "Grão de bico",
    group: "cereais",
    image: "grao_de_bico.jpg",
  },
  { id: "075", name: "Lentilha", group: "cereais", image: "lentilha.jpg" },
  { id: "076", name: "Milho", group: "cereais", image: "milho.jpg" },
  {
    id: "077",
    name: "Queijo Colonial",
    group: "origem animal",
    image: "queijo_colonial.jpg",
  },
  { id: "078", name: "Ricota", group: "origem animal", image: "ricota.jpg" },
  { id: "079", name: "Leite", group: "origem animal", image: "leite.jpg" },
  { id: "080", name: "Mel", group: "origem animal", image: "mel.jpg" },
  { id: "081", name: "Galinha", group: "carnes", image: "galinha.jpg" },
  { id: "082", name: "Ovelha", group: "carnes", image: "ovelha.jpg" },
  { id: "083", name: "Boi", group: "carnes", image: "boi.jpg" },
  {
    id: "084",
    name: "Batata doce",
    group: "vegetais",
    image: "batata_doce.jpg",
  },
];

export const productsWithVariety = [
  "001",
  "002",
  "009",
  "010",
  "003",
  "016",
  "017",
  "020",
  "024",
  "037",
  "038",
  "051",
  "060",
  "061",
  "004",
  "062",
  "064",
  "066",
  "070",
  "071",
  "073",
  "007",
  "008",
];

export const animalProducts = ["077", "078", "079", "080"];
export const meats = ["081", "082", "083"];
