import { SuccessReturn, UseCaseHandler } from "@shared/core/UseCase";
import { ecooAPIHTTPProvider } from "@shared/interfaces/ecoo-api-http-provider";

import { FarmDTO } from "@shared/domain/dtos/farm-dto";
import { OrderCompleteDTO } from "@shared/domain/dtos/order-complete-dto";

export const listFarmOrders: UseCaseHandler<
  { access_token: string; farm_id: string; cycle_id: string },
  { farm: FarmDTO; orders: OrderCompleteDTO[] }
> = async ({ access_token, farm_id, cycle_id }, stubbed) => {
  if (stubbed) {
    const farm: FarmDTO = {
      id: "1",
      name: "Fazenda",
      caf: "123456",
      active: true,
      admin_id: "1",
      tax: 0.1,
      created_at: new Date(),
      updated_at: null,
    };
    const orders: OrderCompleteDTO[] = [
      {
        id: "1",
        user_id: "1",
        amount: 1,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "1",
          farm_id: "1",
          cycle_id: "1",
          price: 1,
          amount: 1,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "1",
            name: "Pé de Alface",
            pricing: "UNIT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "2",
        user_id: "2",
        amount: 2,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "2",
          farm_id: "1",
          cycle_id: "1",
          price: 2,
          amount: 2,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "2",
            name: "Tomate",
            pricing: "WEIGHT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "3",
        user_id: "3",
        amount: 3,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "3",
          farm_id: "1",
          cycle_id: "1",
          price: 3,
          amount: 3,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "1",
            name: "Pé de Alface",
            pricing: "UNIT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "4",
        user_id: "4",
        amount: 4,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "4",
          farm_id: "1",
          cycle_id: "1",
          price: 4,
          amount: 4,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "2",
            name: "Tomate",
            pricing: "WEIGHT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "5",
        user_id: "5",
        amount: 5,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "5",
          farm_id: "1",
          cycle_id: "1",
          price: 5,
          amount: 5,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "3",
            name: "Cenoura",
            pricing: "UNIT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "6",
        user_id: "6",
        amount: 6,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "6",
          farm_id: "1",
          cycle_id: "1",
          price: 6,
          amount: 6,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "3",
            name: "Cenoura",
            pricing: "UNIT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "7",
        user_id: "7",
        amount: 7,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "7",
          farm_id: "1",
          cycle_id: "1",
          price: 7,
          amount: 7,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "1",
            name: "Pé de Alface",
            pricing: "UNIT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "8",
        user_id: "8",
        amount: 8,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "8",
          farm_id: "1",
          cycle_id: "1",
          price: 8,
          amount: 8,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "2",
            name: "Tomate",
            pricing: "WEIGHT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "9",
        user_id: "9",
        amount: 9,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "9",
          farm_id: "1",
          cycle_id: "1",
          price: 9,
          amount: 9,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "1",
            name: "Pé de Alface",
            pricing: "UNIT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
      {
        id: "10",
        user_id: "10",
        amount: 10,
        status: "PENDING",
        created_at: new Date(),
        updated_at: null,
        offer: {
          id: "10",
          farm_id: "1",
          cycle_id: "1",
          price: 10,
          amount: 10,
          description: "description",
          created_at: new Date(),
          updated_at: null,
          product: {
            id: "3",
            name: "Cenoura",
            pricing: "UNIT",
            image: "image",
            created_at: new Date(),
            updated_at: null,
          },
        },
      },
    ];

    const farmOrders = {
      farm: farm,
      orders: orders,
    };

    return new SuccessReturn(farmOrders);
  }

  const farmOrders = (
    await ecooAPIHTTPProvider.listFarmOrders(access_token, farm_id, cycle_id)
  ).data;

  return new SuccessReturn(farmOrders);
};
